name: Move Submissions

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  move-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move submission files
        run: |
          mkdir -p pending/
          shopt -s nullglob
          for f in submissions/*.json; do
            echo "Moving $f to pending/"
            mv "$f" pending/
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pending/*.json
          git rm submissions/*.json || true
          git commit -m "Move new submissions to pending" || echo "Nothing to commit"
          git push
