name: Save Form Submission

on:
  repository_dispatch:
    types: [new-form-submission]

jobs:
  save_submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode and save submission
        run: |
          mkdir -p pending
          echo "${{ github.event.client_payload.json }}" | base64 --decode > pending/${{ github.event.client_payload.filename }}
          
          if [ "${{ github.event.client_payload.image_base64 }}" != "" ]; then
            echo "${{ github.event.client_payload.image_base64 }}" | base64 --decode > pending/${{ github.event.client_payload.image_filename }}
          fi

      - name: Commit and push submission
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pending/
          git commit -m "Add new form submission"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
